### ISSUE TITLE
Empty jobs maybe created if there are files in ExpRootDir

### ISSUE THREAD

**Issue by JaikrishnaTS** [GRAPLE/GEMT#4]
https://github.com/GRAPLE/GEMT/blob/master/GRAPLE_SCRIPTS/Graple.py#L153

Since count % SimsPerJob == 0 is being checked in every iteration, if the iteration refers to a file and the count is 0, empty job maybe submitted

Indent the block to solve the issue.

**Comment by vahid-dan** [comment]
Fixed in v3.1.0.
